# -*- mode: ruby -*-
# vi: set ft=ruby :

# my boilerplate vagrant files because im really lazy and love to copy stuff

# vagrant api v2
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # base box for vagrant config
  config.vm.box = "hashicorp/precise32"

  # provisioning shell script
  config.vm.provision :shell, path: "bootstrap.sh"
end
