# Prompt
[[ -f "$HOME/.bash_prompt" ]] && source "$HOME/.bash_prompt"
# overwrite path because i dont know what it's gonna be
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH="$HOME/bin:$PATH:$HOME/.npm/bin"
export PATH="$HOME/.rbenv/bin:$PATH"

# project binaries for node
export PATH="$PATH:./node_modules/.bin:./bin"
# rbenv shims
export PATH="$HOME/.rbenv/shims:$PATH"

# i guess i'm a vim user
export EDITOR='vim'

# i speak english in utf8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# init
. $HOME/code/z/z.sh
. $HOME/code/git-completion.bash
. $HOME/code/tmux.completion.bash

# source aliases
source ~/.bash_aliases
